from __future__ import annotations

import json

from .config import ProfileConfig, ProjectConfig, ProviderConfig, RoleConfig
from .routing import agent_identity


GENERATED_MARKER = "Generated by OrchestraKit. Do not edit."
AGENTS_START = "<!-- orchestra-kit:start -->"
AGENTS_END = "<!-- orchestra-kit:end -->"


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_agent(config: ProjectConfig, role: RoleConfig, profile_name: str | None = None) -> str:
    profile = config.profiles[profile_name or role.profile]
    instructions = (
        f"Project: {config.name}\n"
        f"Role: {role.name}\n\n"
        f"{role.prompt.strip()}\n\n"
        "Leaf-agent invariant: do not delegate, spawn agents, broaden scope, or make final "
        "integration decisions. Return evidence to the root Codex orchestrator."
    )
    lines = [
        f"# {GENERATED_MARKER}",
        f"name = {_toml_string(agent_identity(config, role.name, profile.name)[0])}",
        f"description = {_toml_string(role.description)}",
        f"model = {_toml_string(profile.model)}",
        f"model_reasoning_effort = {_toml_string(profile.effort)}",
        f"sandbox_mode = {_toml_string(role.sandbox)}",
        f"developer_instructions = {_toml_string(instructions)}",
    ]
    if profile.provider is not None:
        provider = config.providers[profile.provider]
        lines.append(f"model_provider = {_toml_string(provider.name)}")
        if provider.model_catalog_json is not None:
            lines.append(
                f"model_catalog_json = {_toml_string(provider.model_catalog_json)}"
            )
        lines.extend(["", *_render_provider(provider)])
    return "\n".join(lines) + "\n"


def _render_provider(provider: ProviderConfig) -> list[str]:
    lines = [
        f"[model_providers.{provider.name}]",
        f"name = {_toml_string(provider.display_name)}",
        f"base_url = {_toml_string(provider.base_url)}",
        f"wire_api = {_toml_string(provider.wire_api)}",
    ]
    if provider.env_key is not None:
        lines.append(f"env_key = {_toml_string(provider.env_key)}")
    if provider.supports_standalone_web_search:
        lines.append("supports_standalone_web_search = true")
    return lines


def render_skill(config: ProjectConfig) -> str:
    agents = "\n".join(
        f"- `orchestra_{role.name}`: {role.description} Profile: `{role.profile}`."
        for role in config.roles.values()
    )
    if config.routing.enabled:
        variants = "\n".join(
            f"- `{agent_identity(config, role.name, profile)[0]}`: `{role.name}` with `{profile}`."
            for role in config.roles.values()
            for profile in config.profiles if profile != role.profile
        )
        agents += "\n\nConfigured routing variants:\n\n" + variants
    provider_limits = []
    for profile in config.profiles.values():
        if profile.provider is None:
            continue
        provider = config.providers[profile.provider]
        capabilities = (
            ", ".join(f"`{item}`" for item in provider.capabilities)
            or "no capabilities declared"
        )
        provider_limits.append(
            f"- Profile `{profile.name}` uses provider `{provider.name}` with {capabilities}."
        )
    provider_section = ""
    if provider_limits:
        provider_section = (
            "\n## Provider capability boundaries\n\n"
            + "\n".join(provider_limits)
            + "\n\nDo not send a task to a provider-backed leaf when the task requires an "
            "undeclared capability. Choose a compatible role/profile or keep the work in the root session.\n"
        )
    policy_files = "\n".join(
        f"{index}. `{path}`"
        for index, path in enumerate(config.context.policy_files, start=1)
    )
    policy_section = ""
    if policy_files:
        policy_section = f"""
## Project policy overlays

Read these project-owned policy files in order before planning or delegating:

{policy_files}

Later policy files may narrow earlier ones, but none can override higher-priority
instructions or the nearest applicable `AGENTS.md`.
"""
    return f"""---
name: orchestrate-project
description: Coordinate substantial multi-step repository work with Codex as the root orchestrator and project-configured leaf agents. Use when work has independent research, implementation, testing, or review tracks; keep small tightly coupled tasks local.
---

<!-- {GENERATED_MARKER} -->

# Codex-root orchestration

Remain the sole root orchestrator. You own decomposition, delegation decisions,
verification, integration, and the final response. Never transfer that authority
to a leaf agent.

Read `.orchestra/project.toml` before delegating. It is the source of truth for
role-to-profile mappings. The generated custom agents already contain the
configured model, reasoning effort, sandbox, and optional provider.
Use the installed `$orchestra` skill's launcher for routing and durable state;
the execution contract below defines the arguments and policy. Check that the
host has loaded a custom agent before invoking it. Newly generated definitions
may need a new chat. Do not claim a profile switch when work stays in the root.
For exact configured native CLI launches with bounded repair, read the installed
`orchestra` skill's execution reference and use `execute PROJECT --input JOB.json`.

Before implementation or review delegation, read
`references/execution-contract.md`. It defines the active `{config.workflow.mode}`
workflow, task and result schemas, review gates, repair limit, evidence rules,
and Git authority boundaries.
{policy_section}

## Available leaf agents

{agents}

At most {config.max_parallel} leaf agents may run concurrently.
Preferred root-planning strength label: `{config.default_profile}`. This label
does not replace the model selected for the active root Codex chat.
{provider_section}

## Delegation rule

Keep small or tightly coupled work in the root session. Use multi-agent
delegation when two or more independent, substantial tracks will materially
improve speed or verification quality. Give every leaf a bounded brief with:

- goal and explicit scope;
- sources of truth and relevant paths;
- acceptance criteria;
- required verification;
- constraints and forbidden changes.

Leaf agents must not delegate further. Treat their reports as evidence, not as
accepted truth. Inspect relevant diffs and verification output before integrating
their work. Preserve unrelated user changes and follow all nearer project
instructions.
"""


def render_execution_contract(config: ProjectConfig) -> str:
    workflow = config.workflow
    review_levels = (
        ", ".join(f"`{level}`" for level in workflow.review_levels) or "none"
    )
    policy_files = (
        "\n".join(
            f"{index}. `{path}`"
            for index, path in enumerate(config.context.policy_files, start=1)
        )
        or "No additional project policy files are configured."
    )
    mode_rules = {
        "adaptive": (
            "Keep small or tightly coupled work in the root session. Delegate only "
            "bounded, substantial work when separation improves speed or independent "
            "verification."
        ),
        "strict": (
            "Send each implementation leaf through worker then independent leaf review. "
            "Do not accept the overall result before the final review gate passes."
        ),
        "program": (
            "Plan explicit leaves and work packages. Review every leaf, each completed "
            "work package, and the final integrated result before declaring completion."
        ),
    }[workflow.mode]
    worker_freshness = (
        "Use a fresh worker session for each new leaf; a repair cycle may return to the "
        "same worker for that leaf."
        if workflow.fresh_worker_per_leaf
        else "The root may reuse a worker session across leaves when its context remains bounded."
    )
    reviewer_freshness = (
        "Use a fresh reviewer session for every review and re-review."
        if workflow.fresh_reviewer_always
        else "A reviewer session may be reused when independence is not reduced."
    )
    checkpoint_rule = {
        "manual": (
            "Create Git checkpoints only when the root explicitly decides they are needed "
            "and the user has authorized commits."
        ),
        "after-review": (
            "After a passing review, the root may create a checkpoint only when the user's "
            "request already authorizes commits."
        ),
    }[workflow.checkpoint_policy]
    publication_rule = {
        "human-controlled": (
            "Never push, publish, open a pull request, or deploy without explicit user "
            "authorization."
        ),
        "never": "Do not push, publish, open a pull request, or deploy under this workflow.",
    }[workflow.git_publication]
    return f"""<!-- {GENERATED_MARKER} -->

# Execution contract

Mode: `{workflow.mode}`

{mode_rules}

- Maximum repair cycles: `{workflow.max_repair_cycles}`.
- Observed input-plus-output token threshold before retry: `{workflow.max_observed_tokens if workflow.max_observed_tokens is not None else 'disabled'}`.
- Native attempt / durable queue dispatch limit: `{workflow.max_launches if workflow.max_launches is not None else 'disabled'}`.
- Fresh source-bound completion evidence required: `{str(workflow.require_fresh_evidence).lower()}`.
- Review levels: {review_levels}.
- {worker_freshness}
- {reviewer_freshness}

## Adaptive routing and context

Routing enabled: `{str(config.routing.enabled).lower()}`.
Increasing profile order: {', '.join(f'`{p}`' for p in config.routing.profile_order)}.
Brief limit: `{config.context.max_brief_chars}` characters.
Result limit: `{config.context.max_result_chars}` characters.
Native leaf skill-catalog limit: `{config.context.max_skill_catalog_tokens}` tokens.

Use the installed `orchestra` skill's bundled launcher, or `bin/orchestra` from
an available kit checkout. All commands below follow that launcher:

```text
route PROJECT --role worker --complexity complex --risk high --independent
brief PROJECT --input BRIEF.json
execute PROJECT --input JOB.json --dry-run
execute PROJECT --input JOB.json
task start PROJECT --goal "Concrete outcome"
task list PROJECT
task show PROJECT TASK_ID
task record PROJECT TASK_ID --input RESULT.json --revision REVISION
```

Select complexity and risk from repository evidence. The higher tier determines
the profile and its configured effort; the reviewer keeps its configured floor.
Disabled routing uses only fixed role profiles. Provider capabilities and host
availability must match the task. Respect the returned root/leaf recommendation
and host limits. Small or tightly coupled work remains with the root.

The native runner accepts bounded jobs and actual check argv lists. Shared
checkout jobs serialize. Prepared isolated worktrees can run within global
capacity, with explicit write paths and checks after integration. It disables
delegation, pins configuration, journals phases and supports explicit cancellation.
A verified leaf still needs root acceptance and configured review gates.
Built-in profiles need a POSIX host. Custom providers use the native Responses
protocol; credentials come from environment variables or the macOS Keychain.
When a selected profile has a custom provider, use `execute PROJECT --input JOB.json`
to launch it. Do not substitute a built-in host agent for that provider route.
The native runner injects the resolved credential only into its child process.
If the native runner is unavailable, report that limitation; never silently
fall back to another provider.

For substantial jobs, supply evidence_files; read-only reviews may use
review_files. Execution writes an evidence_ref covering exact source and check
artifact hashes. Review reports must start with VERDICT: PASS or VERDICT: FAIL.
Attach refs to required checks and reviews in task results and recheck them at
completion. Run root checks with evidence run PROJECT --input CHECKS.json.
Configured fresh evidence refuses missing bindings and changed subjects or logs.

Use the installed execution reference for optional DAG queue, fenced leases,
worktree isolation, compact handoff and calibration commands. Dependency readiness,
budget checks and capacity reservation run locally without a decision-model call.
Lease expiry alone never authorizes replay. Keep these controls out of small
coupled tasks. JSON result contracts may declare representation-only aliases;
contract failures return to the root without model escalation.

After a failure use `--failure context|implementation|capability|environment`,
`--previous-profile PROFILE`, and `--attempt N` (zero at first failure).
Gather missing context before raising strength. Repair the first implementation
failure; escalate repeated implementation failures within the repair budget.
Return capability failures to the root to diagnose unavailable tools or host
features. Stop for environment failures or an exhausted budget. If configured,
the observed-token threshold stops another retry when reached; incomplete
counters also stop retries. It cannot cap the first call or billing cost.

Keep stable policy and tool instructions together before the changing brief
when prefix caching is available. Send relevant paths and excerpts, not full
chat histories. Preserve constraints when narrowing context. Provider Batch is
only suitable for independent, nonurgent, authorized API submissions. This kit
does not enable server caching, submit Batch jobs, or guarantee billing savings.

For substantial work, keep an explicit task UUID and record compact, verified
progress in `.orchestra/runs/UUID.json`. Separate chats use separate UUIDs;
never infer the current task from recency. Resume by reading compact state and
rechecking the current repository. Recording requires the current revision.
Completion requires passing required checks, satisfied acceptance criteria,
all configured review gates, and no unresolved next steps or failures. State
validation does not execute checks: the root must inspect actual evidence.
Record runtime metrics only when known, otherwise null. Read the installed
`orchestra` skill's state reference for the full result schema.

## Source of truth

Treat chat context as disposable. Repository instructions, current files, Git
diffs, test output, and task artifacts are durable evidence. Re-read relevant
sources before decisions after interruption or context loss.

Apply configured project policy overlays in this order:

{policy_files}

Later listed policies may narrow earlier policies. They never override system,
developer, current user, or nearer `AGENTS.md` instructions.

## Leaf task brief

Every delegated leaf receives exactly these sections:

```text
GOAL
SOURCES OF TRUTH
SCOPE
ACCEPTANCE CRITERIA
VERIFICATION
CONTEXT
```

The root supplies concrete paths and forbidden changes. A leaf stays inside the
brief, never delegates, preserves unrelated work, and reports a decision to the
root instead of asking the user directly.

## Review and repair

A reviewer receives the original brief plus the exact diff or artifact being
reviewed. The reviewer is independent, read-only, never fixes findings, and must
return exactly `VERDICT: PASS` or `VERDICT: FAIL`. A PASS has no blocking
findings; observations remain non-blocking.

On FAIL, the root sends only the blocking findings and original acceptance
criteria into a bounded repair cycle, then requests a new review. Stop after
`{workflow.max_repair_cycles}` failed repair cycles and report the unresolved
blocker to the user. Never relabel an unverified result as complete.

## Evidence

Separate observed facts, command output, and test results from inference. Report
commands and outcomes precisely. Missing or unavailable verification is a gap,
not a pass. The root independently inspects relevant diffs and evidence before
integration and owns the final completion claim.

## Git authority

{checkpoint_rule}

Leaf agents never stage, commit, push, publish, open pull requests, or deploy
unless the root brief explicitly grants the specific action within authority the
user already provided. {publication_rule}
"""


def render_skill_ui() -> str:
    return f"""# {GENERATED_MARKER}
interface:
  display_name: "Orchestrate Project"
  short_description: "Coordinate work with configured Codex roles"
  default_prompt: "Use $orchestrate-project to coordinate this multi-step task."
policy:
  allow_implicit_invocation: true
"""


def render_agents_block(config: ProjectConfig) -> str:
    role_names = ", ".join(f"`orchestra_{name}`" for name in config.roles)
    return f"""{AGENTS_START}
## OrchestraKit

For substantial work with independent tracks, use the `$orchestrate-project`
skill and the generated custom agents: {role_names}. Codex remains the sole root
orchestrator and must verify leaf-agent results before integration. Keep small or
tightly coupled work in the root session. Project orchestration settings live in
`.orchestra/project.toml`; the generated execution contract defines workflow
gates and authority boundaries. After editing settings, run `orchestra sync`
from the kit.
{AGENTS_END}"""
