import React,{useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {ChevronDown,Check} from 'lucide-react';
let sequence=0;
export function Dropdown({label,value,options,onChange,disabled=false}) {
 const [open,setOpen]=useState(false),[active,setActive]=useState(0),[position,setPosition]=useState({});const button=useRef(),list=useRef(),id=useRef('menu-'+(++sequence));
 const selected=options.findIndex(o=>o.value===value),chosen=options[selected];
 function show(){if(disabled)return;setActive(Math.max(0,selected));setOpen(true);}
 function choose(index){const option=options[index];if(option){onChange(option.value);setOpen(false);button.current.focus();}}
 useEffect(()=>{if(!open)return;const update=()=>{const r=button.current.getBoundingClientRect();const height=Math.min(320,options.length*45+16);setPosition({top:r.bottom+height>innerHeight-10?Math.max(10,r.top-height-6):r.bottom+6,left:Math.max(10,Math.min(r.left,innerWidth-Math.max(r.width,220)-10)),width:Math.min(Math.max(r.width,220),innerWidth-20),maxHeight:Math.min(320,innerHeight-20)});};update();const outside=e=>{if(!button.current.contains(e.target)&&!list.current?.contains(e.target))setOpen(false);};document.addEventListener('pointerdown',outside);window.addEventListener('resize',update);window.addEventListener('scroll',update,true);return()=>{document.removeEventListener('pointerdown',outside);window.removeEventListener('resize',update);window.removeEventListener('scroll',update,true);};},[open,options.length]);
 useEffect(()=>{if(open)list.current?.querySelector('[data-active="true"]')?.scrollIntoView({block:'nearest'});},[active,open]);
 function key(e){if(['ArrowDown','ArrowUp','Home','End','Escape','Enter',' '].includes(e.key)){e.preventDefault();if(e.key==='Escape'){setOpen(false);return;}if(!open){show();return;}if(e.key==='ArrowDown')setActive(n=>(n+1)%options.length);else if(e.key==='ArrowUp')setActive(n=>(n+options.length-1)%options.length);else if(e.key==='Home')setActive(0);else if(e.key==='End')setActive(options.length-1);else choose(active);}if(e.key==='Tab')setOpen(false);}
 return <div className="dropdown"><button ref={button} type="button" className="dropdown-trigger" role="combobox" aria-label={label} aria-expanded={open} aria-controls={open?id.current:undefined} aria-activedescendant={open?id.current+'-'+active:undefined} aria-haspopup="listbox" disabled={disabled} onKeyDown={key} onClick={()=>open?setOpen(false):show()}><span>{chosen?.label||'Выберите'}</span><ChevronDown size={16}/></button>{open&&createPortal(<div ref={list} className="dropdown-menu" id={id.current} role="listbox" aria-label={label} style={position}>{options.map((o,i)=><button type="button" role="option" id={id.current+'-'+i} key={o.value} tabIndex={-1} data-active={active===i} aria-selected={value===o.value} onPointerMove={()=>setActive(i)} onClick={()=>choose(i)}><span>{o.label}{o.description&&<small>{o.description}</small>}</span>{value===o.value&&<Check size={16}/>}</button>)}</div>,document.body)}</div>;
}
